export default {
  products: [
    {
      _id: "111111111111111111111111",
      name: "Hiskywin Full Zip Running Shirts Thermal Workout",
      category: "Shirts",
      image: "https://tinyurl.com/mvj5s89a",
      price: 59,
      brand: "Hiskywin",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "222222222222222222222222",
      name: "Nike Full-Zip Hoodie Mens Workout Sweatshirt",
      category: "Shirts",
      image:
        "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/5b22abb2-eea4-4552-8e84-cae4887d034e/dry-dri-fit-hooded-fitness-hoodie-2PfZ40.png",
      price: 70,
      brand: "Nike",
      rating: 5,
      numReviews: 51,
    },
    {
      _id: "3",
      name: "Adidas Mens Long Sleeve Hoodie",
      category: "Shirts",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqcwmaTQ1-Dr5Q6-VqSxuqFLxOY5mCN7-U596EpZDvtP_LfyE6JOJsFlje6qHNCZJNZR8&usqp=CAU",
      price: 59,
      brand: "Adidas",
      rating: 4,
      numReviews: 45,
    },
    {
      _id: "4",
      name: "Under Armour Mens Sportstyle Tricot Joggers",
      category: "Pants",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnbxwMNnibMs1GqA5RYGCpLIYamnQu5V-JBZFllxUcUwqsXv9gM5liyL0gHY1ENZcf76E",
      price: 90,
      brand: "Under Armour",
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: "5",
      name: "Champion Mens Graphic Powerblend Fleece Jogger",
      category: "Pants",
      image: "https://tinyurl.com/yc2a5css",
      price: 119,
      brand: "Champion",
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
    },
    {
      _id: "6",
      name: "Aelfric Eden Mens Joggers Pants Long Multi-Pockets",
      category: "Pants",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYWDK5-EfdlyFUFn76uunMT-qXx1DqF1qztw1sNtNMsw&s",
      price: 85,
      brand: "Aelfric Eden",
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
    },
  ],
};
